### ISSUE TITLE
Not getting packages from custom Nuget feeds

### ISSUE THREAD

**Issue by jdssbatman** [365businessdev/alget#3]
I have added the necessary URL to the "365businessdev.alget.nugetFeeds" setting, as well as the apikey, but I am not getting any of the packages from this custom feed.

**Comment by sirhc101** [comment]
I changed the method to fetch packages recently, looks like the authentication part got lost 🫣

**Comment by sirhc101** [comment]
Fixed with version 0.0.4

**Comment by jdssbatman** [comment]
@sirhc101

I have used the updated version of the extension, but I still get zero packages.

**Comment by sirhc101** [comment]
Hm, that's weird. I tried with a DevOps NuGet feed, using the PAT.
What type of NuGet feed are you using?

Let me look into that again. Sorry!

**Comment by juliandittmann** [comment]
Hi, @sirhc101 

i have successfully tested your fix against a GitHub NuGet feed with an apikey.

ALGet - v0.0.4

![image](https://github.com/user-attachments/assets/a26cdec5-c2f3-4632-8fbf-b7eb909b8f83)

**Comment by DarthNuts** [comment]
Still facing same problem using version 0.0.4 and Azure Devops Private Project and Feed. If i switch my project type to Public then it starts working with and without apiKey.
I've double checked my url and token using nuget app and PS script. 
```
$uri = "uri"
$personalAccessToken = "PAT"

$headers = @{
    Authorization = "Basic " + [Convert]::ToBase64String([Text.Encoding]::ASCII.GetBytes(":$($personalAccessToken)"))
}

$response = Invoke-RestMethod -Uri $uri -Headers $headers -Method Get

Write-Host $response.resources 

```

**Comment by sirhc101** [comment]
Hi @DarthNuts 

Thanks for reporting this issue.
I confirm the implementation for private feeds w/  authentication is not good in v0.0.4.
Anyway, for short term this should work:
```json
"365businessdev.alget.nugetFeeds": [
	{
		"name": "Your NuGet feed",
		"url": "https://dev.azure.com/<yourOrg>/_packaging/<yourFeed>/nuget/v3/index.json",
		"apiKey": "Basic <base64-encoded-PAT>"
	}
]
```

However, I completely refactored ALGet over the last months and created a new method to consume the feeds. This refactoring will be released with the first major version of ALGet. Unfortunatly, I do not have a lot of spare time at the moment, but I hope I will be able to finalize everything until end of February.

So, stay tuned 😎
